// Code generated by MockGen. DO NOT EDIT.
// Source: configuration_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/protengplus/proteng-conductor/models"
)

// MockConfigurationRepository is a mock of ConfigurationRepository interface.
type MockConfigurationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationRepositoryMockRecorder
}

// MockConfigurationRepositoryMockRecorder is the mock recorder for MockConfigurationRepository.
type MockConfigurationRepositoryMockRecorder struct {
	mock *MockConfigurationRepository
}

// NewMockConfigurationRepository creates a new mock instance.
func NewMockConfigurationRepository(ctrl *gomock.Controller) *MockConfigurationRepository {
	mock := &MockConfigurationRepository{ctrl: ctrl}
	mock.recorder = &MockConfigurationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationRepository) EXPECT() *MockConfigurationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConfigurationRepository) Create(configuration *models.Configuration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", configuration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockConfigurationRepositoryMockRecorder) Create(configuration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigurationRepository)(nil).Create), configuration)
}

// DeleteByJobId mocks base method.
func (m *MockConfigurationRepository) DeleteByJobId(jobId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByJobId", jobId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByJobId indicates an expected call of DeleteByJobId.
func (mr *MockConfigurationRepositoryMockRecorder) DeleteByJobId(jobId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByJobId", reflect.TypeOf((*MockConfigurationRepository)(nil).DeleteByJobId), jobId)
}

// GetAll mocks base method.
func (m *MockConfigurationRepository) GetAll(query map[string]interface{}) ([]*models.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", query)
	ret0, _ := ret[0].([]*models.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockConfigurationRepositoryMockRecorder) GetAll(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockConfigurationRepository)(nil).GetAll), query)
}
