// Code generated by MockGen. DO NOT EDIT.
// Source: mutation_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/protengplus/proteng-conductor/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// MockMutationRepository is a mock of MutationRepository interface.
type MockMutationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMutationRepositoryMockRecorder
}

// MockMutationRepositoryMockRecorder is the mock recorder for MockMutationRepository.
type MockMutationRepositoryMockRecorder struct {
	mock *MockMutationRepository
}

// NewMockMutationRepository creates a new mock instance.
func NewMockMutationRepository(ctrl *gomock.Controller) *MockMutationRepository {
	mock := &MockMutationRepository{ctrl: ctrl}
	mock.recorder = &MockMutationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutationRepository) EXPECT() *MockMutationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMutationRepository) Create(mutation *models.Mutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMutationRepositoryMockRecorder) Create(mutation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMutationRepository)(nil).Create), mutation)
}

// Delete mocks base method.
func (m *MockMutationRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMutationRepositoryMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMutationRepository)(nil).Delete), id)
}

// DeleteByJobId mocks base method.
func (m *MockMutationRepository) DeleteByJobId(jobId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByJobId", jobId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByJobId indicates an expected call of DeleteByJobId.
func (mr *MockMutationRepositoryMockRecorder) DeleteByJobId(jobId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByJobId", reflect.TypeOf((*MockMutationRepository)(nil).DeleteByJobId), jobId)
}

// FindById mocks base method.
func (m *MockMutationRepository) FindById(id string) (*models.Mutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", id)
	ret0, _ := ret[0].(*models.Mutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockMutationRepositoryMockRecorder) FindById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockMutationRepository)(nil).FindById), id)
}

// GetAll mocks base method.
func (m *MockMutationRepository) GetAll(query map[string]interface{}) ([]*models.Mutation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", query)
	ret0, _ := ret[0].([]*models.Mutation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMutationRepositoryMockRecorder) GetAll(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMutationRepository)(nil).GetAll), query)
}

// Update mocks base method.
func (m *MockMutationRepository) Update(id string, mutation *models.Mutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMutationRepositoryMockRecorder) Update(id, mutation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMutationRepository)(nil).Update), id, mutation)
}

// FindBestAssayScore mocks base method.
func (m *MockMutationRepository) FindBestAssayScore(jobIDs []primitive.ObjectID) (*models.BestAssayScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBestAssayScore", jobIDs)
	ret0, _ := ret[0].(*models.BestAssayScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBestAssayScore indicates an expected call of FindBestAssayScore.
func (mr *MockMutationRepositoryMockRecorder) FindBestAssayScore(jobIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBestAssayScore", reflect.TypeOf((*MockMutationRepository)(nil).FindBestAssayScore), jobIDs)
}