// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go

// Package mock_publisher is a generated GoMock package.
package mock_publisher

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishDefaultExchange mocks base method.
func (m *MockPublisher) PublishDefaultExchange(ctx context.Context, queueName string, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDefaultExchange", ctx, queueName, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDefaultExchange indicates an expected call of PublishDefaultExchange.
func (mr *MockPublisherMockRecorder) PublishDefaultExchange(ctx, queueName, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDefaultExchange", reflect.TypeOf((*MockPublisher)(nil).PublishDefaultExchange), ctx, queueName, body)
}
